server:
  port: 8010

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auction?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  profiles:
    active: local  # 开发环境使用 dev，生产环境改为 prod

logging:
  level:
    com.shanshan.auction: INFO
    org.springframework: WARN
    org.mybatis: WARN
    com.baomidou.mybatisplus: WARN

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml
  type-enums-package: com.shanshan.auction.model.enums

jwt:
  # 使用Base64编码的安全密钥，至少32字节（256位）
  secret: "bG9jYWwtc2VjcmV0LWtleS1mb3ItYXVjdGlvbi1hcHAtc2hhbnNoYW4tZGV2ZWxvcG1lbnQ="
  expiration: 86400000 # 24小时
  refresh-expiration: 2592000000  # 30天 (用于刷新token) 